# Generated by Django 4.2.1 on 2023-07-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(),
        ),
    ]
